// Code generated by hertz generator.

package main

import (
	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/app/server"
)

func main() {
	h := server.Default(server.WithHostPorts(":3000"))

	// 静态文件目录
	fs := &app.FS{Root: "./website", IndexNames: []string{"index.html"}}
	h.StaticFS("/", fs)

	// 注册路由
	register(h)

	// 启动服务
	h.Spin()
}
